# Generated by Django 4.2.7 on 2026-02-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=50, verbose_name='Персонаж')),
                ('text_content', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Текст пользователя',
                'verbose_name_plural': 'Тексты пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
